# Generated by Django 3.1.7 on 2021-02-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='tokenmodel',
            name='username',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
