# Generated by Django 3.1.7 on 2021-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210330_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(default='profiles/ava.png', upload_to='profiles'),
        ),
    ]
