# Generated by Django 3.1.7 on 2021-05-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210503_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='image_4',
        ),
    ]
