# Generated by Django 3.1.7 on 2021-03-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_manufacturermodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='properties',
            field=models.ManyToManyField(null=True, related_name='products', to='shop.PropertyItemModel'),
        ),
    ]
