# Generated by Django 3.1.7 on 2021-04-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210412_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.subcategorymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.manufacturermodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.producttypemodel'),
        ),
    ]
