# Generated by Django 3.1.7 on 2021-04-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productmodel_best'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
