# Generated by Django 3.1.7 on 2021-05-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_categorymodel_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='title_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
