# Generated by Django 3.1.7 on 2021-05-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210506_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='characteristics_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='characteristics_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='characteristics_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
