# Generated by Django 3.1.7 on 2021-05-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20210510_1441'),
        ('shop', '0018_auto_20210506_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='vendors.vendormodel'),
        ),
    ]
