# Generated by Django 3.1.7 on 2021-05-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20210510_1441'),
        ('shop', '0019_productmodel_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='vendor',
        ),
        migrations.CreateModel(
            name='VendorProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendormodel')),
            ],
        ),
    ]
