# Generated by Django 3.1.7 on 2021-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210512_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturermodel',
            name='avatar',
            field=models.ImageField(default='manufacturer/default_ava.png', upload_to='manufacturer/avatar/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='manufacturermodel',
            name='banner',
            field=models.ImageField(default='manufacturer/default_banner.png', upload_to='manufacturer/landing/avatar/%Y/%m/%d'),
        ),
    ]
