# Generated by Django 3.1.7 on 2021-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_vendorproductmodel_search_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturermodel',
            old_name='banner',
            new_name='banner1',
        ),
        migrations.AddField(
            model_name='manufacturermodel',
            name='banner2',
            field=models.ImageField(default='manufacturer/default_banner.png', upload_to='manufacturer/landing/avatar/%Y/%m/%d'),
        ),
    ]
