# Generated by Django 3.1.7 on 2021-06-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20210510_1441'),
        ('shop', '0026_auto_20210607_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='count',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendormodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countstatusmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel'),
        ),
        migrations.DeleteModel(
            name='VendorProductModel',
        ),
    ]
