# Generated by Django 3.1.7 on 2021-06-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20210611_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/profile/avatar/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/profile/banner/%Y/%m/%d'),
        ),
    ]
