# Generated by Django 3.1.7 on 2021-04-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210402_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
