# Generated by Django 3.1.7 on 2021-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_ordermodel_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
